DEBUG: true
SLOW_REQUEST_THRESHOLD: 3.5

VERIFICATION_LINK: http://127.0.0.1:8000/v1/auth/verify
LOGIN_CODE_LINK: http://127.0.0.1:8000/v1/auth/login/verify

VERIFICATION_TOKEN_EXPIRE_MINUTES: 10
LOGIN_CODE_EXPIRE_MINUTES: 5

JWT_TOKEN_EXPIRE_MINUTES: 15
REFRESH_TOKEN_EXPIRE_DAYS: 7
ALGORITHM: HS256

AVATAR_PRESIGNED_PUT_URL_LIFETIME_MINUTES: 15
AVATAR_PRESIGNED_GET_URL_LIFETIME_MINUTES: 60
